services:
  - type: web
    name: stockpy
    env: docker
    plan: free
    repo: https://github.com/yourname/realtime-index-app
    branch: main
    autoDeploy: true
    startCommand: streamlit run app/main.py --server.port=10000 --server.address=0.0.0.0