name: StockPy Daily Scan

on:
  schedule:
    # Runs every day at 10:00 UTC (adjust if needed)
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  run-stockpy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run StockPy daily top-50 scan
        run: python main.py --top50

